"use strict";
exports.__esModule = true;
var circle_1 = require("./circle");
var rectangle_1 = require("./rectangle");
var objCircle = new circle_1.Circle(2);
objCircle.Myarea();
objCircle.Display();
var objRect = new rectangle_1.Rectangle(2, 3);
objRect.Myarea();
objRect.Display();
